apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: balancit
  labels:
    app: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: ml-service:latest
          imagePullPolicy: Never
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
            - name: REDIS_HOST
              value: "redis.balancit"
            - name: REDIS_PORT
              value: "6379"
            - name: INTERVAL_SECONDS
              value: "5"
          resources:
            requests:
              cpu:    "100m"
              memory: "128Mi"
            limits:
              cpu:    "500m"
              memory: "256Mi"
